Settings profile - statisctics methods created
MasterCoookie/bezsciemy pull request #16
Opened 2023-01-25 17:32 UTC by MasterCoookie

2023-01-25 19:01 UTC, tomazaw approved these changes

2023-01-25 19:16 UTC, macibol775 requested changes
w 1 miejscu jest liczniki postów zaakceptowanych i ogółem; nie ma liczby akceptacji
w 2 jest getter liczby postów zaakceptowanych nazwany niespójnie getPostsCount i jest getter liczby akceptacji

czy przetestowano działanie await Post.countDocuments({ upVotes: this._id }); dla arrayów?

2023-01-26 16:36 UTC, MasterCoookie commented
> w 1 miejscu jest liczniki postów zaakceptowanych i ogółem; nie ma liczby akceptacji w 2 jest getter liczby postów zaakceptowanych nazwany niespójnie getPostsCount i jest getter liczby akceptacji
> 
> czy przetestowano działanie await Post.countDocuments({ upVotes: this._id }); dla arrayów?



> w 1 miejscu jest liczniki postów zaakceptowanych i ogółem; nie ma liczby akceptacji w 2 jest getter liczby postów zaakceptowanych nazwany niespójnie getPostsCount i jest getter liczby akceptacji
> 
> czy przetestowano działanie await Post.countDocuments({ upVotes: this._id }); dla arrayów?



> w 1 miejscu jest liczniki postów zaakceptowanych i ogółem; nie ma liczby akceptacji w 2 jest getter liczby postów zaakceptowanych nazwany niespójnie getPostsCount i jest getter liczby akceptacji
> 
> czy przetestowano działanie await Post.countDocuments({ upVotes: this._id }); dla arrayów?

Mamy getter dla liczby akceptacji dokonanych przez danego usera; wraz z pozostałymi wystarczą na nasze potrzeby


Nazwa zmieniona na sensowniejszą

countDocuments testowałem ostro, bo się nie spodziewałem, że to może być aż tak proste

2023-01-26 19:14 UTC, macibol775 commented
ok

2023-01-26 19:14 UTC, macibol775 approved these changes
ok

2023-01-26 19:17 UTC, merged